services:
  postgres:
    image: postgres:16.4-alpine3.20
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PW}
      - PGDATA=/var/lib/postgresql/data/pgdata
    container_name: postgres
    shm_size: 128mb
    volumes:
      - /postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - java-postgres
    ports:
    - 5432:5432

  java-app:
    image: ${DOCKER_HUB_IMG_URL}
    container_name: java-app
    networks:
      - java-postgres
    ports:
    - 8080:8080
    depends_on:
      - postgres

networks:
  java-postgres:
    driver: bridge
